/**
 * src/v3/core/systems/layout.ts
 * Layout System (Stateless Math Utility)
 */
import type { IRegistry, EntityId } from '../ecs/types';

export interface SlotInfo {
    index: number;
    x: number; // Global X (Top-Left of Slot)
    y: number; // Global Y (Top-Left of Slot)
    cx: number; // Center X
    cy: number; // Center Y
    width: number;
    height: number;
}

export class LayoutSystem {
    /**
     * @deprecated Phase 6: Slots are now actual Entities generated by TemplateLoader.
     * Use Registry to find entities with LayoutConfig.strategy === 'slot'.
     */
    static calculateSlots(gridId: EntityId, registry: IRegistry): SlotInfo[] {
        console.warn("[LayoutSystem] calculateSlots is deprecated. Use Slot Entities instead.");
        return [];
    }

    /**
     * Find if any entity matches a target slot entity (Occupancy Check)
     * Now works Purely on Entities (Slot Entity vs Candidate Entity)
     * 
     * @param slotId The ID of the Slot Entity to check
     * @param registry Registry
     * @param candidateIds Candidates to check (usually all Draggables)
     * @param excludeEntityId ID to ignore (usually the one being dragged, if in candidates)
     * @param threshold Distance threshold
     */
    static findOccupant(
        slotId: EntityId,
        registry: IRegistry,
        candidateIds: Iterable<EntityId>,
        excludeEntityId: EntityId | null,
        threshold: number = 40
    ): EntityId | null {
        // 1. Get Slot Position
        const slotTransform = registry.getComponent(slotId, 'Transform');
        if (!slotTransform) return null;

        const slotCx = slotTransform.x + (slotTransform.width || 80) / 2;
        const slotCy = slotTransform.y + (slotTransform.height || 80) / 2;

        for (const id of candidateIds) {
            if (id === excludeEntityId) continue;

            const t = registry.getComponent(id, 'Transform');
            if (!t) continue;

            const w = t.width || 80;
            const h = t.height || 80;
            const cx = t.x + w / 2;
            const cy = t.y + h / 2;

            const dist = Math.hypot(cx - slotCx, cy - slotCy);
            if (dist < threshold) {
                return id;
            }
        }
        return null;
    }
}
